name: Test

on:
  workflow_dispatch

jobs:
  test_job:
    runs-on: macos-latest
    steps:
      - name: brew bash
        run: brew install bash

      - name: Test (shim env)
        shell: /usr/local/bin/bash {0}
        run: |
          echo "DYLD_FALLBACK_LIBRARY_PATH=/tmp" >> $GITHUB_ENV
      

      - name: Test
        shell: /usr/local/bin/bash {0}
        run: |
          echo ${PATHX:-is_empty}
          echo ${DYLD_FALLBACK_LIBRARY_PATH:-is_empty}
